about:
    title: DEA WPS configuration
processes:
    WOfSDrill:
        about:
            identifier: WOfSDrill
            version: '0.4'
            title: Water Observations from Space Pixel Drill
            abstract: |
                Water Observations from Space Pixel Drill
                
                Water Observations from Space (WOfS) provides surface water observations derived from satellite imagery for all of Australia. The current product (Version 2.1.5) includes observations taken from 1986 to the present, from the Landsat 5, 7 and 8 satellites. WOfS covers all of mainland Australia and Tasmania but excludes off-shore Territories.
                
                The WOfS product allows users to get a better understanding of where water is normally present in a landscape, where water is seldom observed, and where inundation has occurred occasionally.
                
                This Pixel Drill will output the water observations for a point through time as graph.
                
                For service status information, see https://status.dea.ga.gov.au.
            store_supported: True
            status_supported: True
            geometry_type: "point"

    FCDrill:
        about:
            identifier: FractionalCoverDrill
            version: '0.2'
            title: Fractional Cover
            abstract: Performs Fractional Cover Polygon Drill
            store_supported: True
            status_supported: True
            geometry_type: polygon
