---
name: docker-latest
on: [workflow_dispatch]

env:
  IMAGE_NAME: opendatacube/wps

jobs:
  docker_latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Login to DockerHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Get unstable git tag
        run: >
          echo "UNSTABLE_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Log the unstable tag
        run: echo $UNSTABLE_TAG

      - name: Export Secrets to enviroment
        run: |
          echo "${{ secrets.DockerPassword }}" | docker login -u "${{ secrets.DockerUser }}" --password-stdin

      - name: Build unstable + latest Docker image tag
        if: github.event_name != 'release'
        uses: whoan/docker-build-with-cache-action@d8d3ad518e7ac382b880720d0751815e656fe032 # v8.1.0
        with:
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: ${{ env.UNSTABLE_TAG }},latest
          build_extra_args: "--build-arg=ENVIRONMENT=deployment"
          push_image_and_stages: false

      - name: Run vulnerability scanner
        if: github.ref == 'refs/heads/master'
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ env.UNSTABLE_TAG }}"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
