---
name: Linting

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

env:
  ORG: opendatacube
  IMAGE: wps

jobs:
  # quality-check:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
  #       with:
  #         fetch-depth: 0

  #     - name: Build WPS image
  #       run: |
  #         docker build --tag ${ORG}/${IMAGE}:latest .
  #     - name: Lint WPS image
  #       run: |
  #         docker run ${ORG}/${IMAGE}:latest /bin/sh -c "./lint-code.sh"

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.9
      - run: python -m pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@e7b7beaaafa52524748b31a381160759d68d61fb # v3.0.0
        with:
          linters: isort
          run: |
            isort --check --diff .

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run bandit
        uses: tj-actions/bandit@0aed5b3da320e0f26781e5aecbbfc1d268ff07e2 # v5.5
        with:
          targets: |  # or a single string "."
            test_package
          options: "-r -s B101,B104"

  pylint:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
      - name: checkout git
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install airflow and run pylint
        run: |
          curl -LsSf https://astral.sh/uv/0.6.6/install.sh | sh
          uv sync
          uv pip install -r requirements.txt
          uv run pylint -j 2 --reports no datacube_wps --disable=C,R,redefined-builtin,fixme,arguments-differ
